### ISSUE TITLE
Roles required

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/feature-flag-backend#93]
These are the roles required for user (vikhyatbhatnagar)
- Create Dynamodb table permission
- We will have to create IAM roles with additional permissions for lambdas
- apigateway: permissions to create API (GET,  PUT, POST, PATCH)
- IAM Tag / Untag role
- AWS lambda (all permissions)
- Cloudformation (all permissions)
- S3 create buckets

<details>
<summary>Attaching the cloudformation template code here 
</summary>

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "PipelineUserArn": {
      "Type": "String"
    },
    "PipelineExecutionRoleArn": {
      "Type": "String"
    },
    "CloudFormationExecutionRoleArn": {
      "Type": "String"
    },
    "ArtifactsBucketArn": {
      "Type": "String"
    },
    "CreateImageRepository": {
      "Type": "String",
      "Default": false,
      "AllowedValues": [
        true,
        false
      ]
    },
    "ImageRepositoryArn": {
      "Type": "String"
    },
    "IdentityProviderThumbprint": {
      "Type": "String"
    },
    "OidcClientId": {
      "Type": "String"
    },
    "OidcProviderUrl": {
      "Type": "String"
    },
    "UseOidcProvider": {
      "Type": "String",
      "AllowedValues": [
        true,
        false
      ]
    },
    "SubjectClaim": {
      "Type": "String"
    },
    "CreateNewOidcProvider": {
      "Type": "String",
      "AllowedValues": [
        true,
        false
      ]
    }
  },
  "Outputs": {
    "PipelineUser": {
      "Description": "ARN of the Pipeline IAM User",
      "Value": {
        "Fn::If": [
          "MissingPipelineUser",
          {
            "Fn::GetAtt": "PipelineUser.Arn"
          },
          {
            "Ref": "PipelineUserArn"
          }
        ]
      }
    },
    "PipelineUserSecretKey": {
      "Description": "AWS Access Key and Secret Key of pipeline user.",
      "Condition": "MissingPipelineUser",
      "Value": {
        "Ref": "PipelineUserSecretKey"
      }
    },
    "CloudFormationExecutionRole": {
      "Description": "ARN of the IAM Role(CloudFormationExecutionRole)",
      "Value": {
        "Fn::If": [
          "MissingCloudFormationExecutionRole",
          {
            "Fn::GetAtt": "CloudFormationExecutionRole.Arn"
          },
          {
            "Ref": "CloudFormationExecutionRoleArn"
          }
        ]
      }
    },
    "PipelineExecutionRole": {
      "Description": "ARN of the IAM Role(PipelineExecutionRole)",
      "Value": {
        "Fn::If": [
          "MissingPipelineExecutionRole",
          {
            "Fn::GetAtt": "PipelineExecutionRole.Arn"
          },
          {
            "Ref": "PipelineExecutionRoleArn"
          }
        ]
      }
    },
    "ArtifactsBucket": {
      "Description": "ARN of the Artifacts bucket",
      "Value": {
        "Fn::If": [
          "MissingArtifactsBucket",
          {
            "Fn::GetAtt": "ArtifactsBucket.Arn"
          },
          {
            "Ref": "ArtifactsBucketArn"
          }
        ]
      }
    },
    "ImageRepository": {
      "Description": "ARN of the ECR image repository",
      "Condition": "ShouldHaveImageRepository",
      "Value": {
        "Fn::If": [
          "MissingImageRepository",
          {
            "Fn::GetAtt": "ImageRepository.Arn"
          },
          {
            "Ref": "ImageRepositoryArn"
          }
        ]
      }
    }
  },
  "Resources": {
    "OidcProvider": {
      "Type": "AWS::IAM::OIDCProvider",
      "Condition": "MissingOidcProvider",
      "Properties": {
        "ClientIdList": [
          {
            "Ref": "OidcClientId"
          }
        ],
        "ThumbprintList": [
          {
            "Ref": "IdentityProviderThumbprint"
          }
        ],
        "Url": {
          "Ref": "OidcProviderUrl"
        }
      }
    },
    "PipelineUser": {
      "Type": "AWS::IAM::User",
      "Condition": "MissingPipelineUser",
      "Properties": {
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          }
        ],
        "Policies": [
          {
            "PolicyName": "AssumeRoles",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "sts:AssumeRole"
                  ],
                  "Resource": "*",
                  "Condition": {
                    "StringEquals": {
                      "aws:ResourceTag/Role": "pipeline-execution-role"
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "PipelineUserAccessKey": {
      "Type": "AWS::IAM::AccessKey",
      "Condition": "MissingPipelineUser",
      "Properties": {
        "Serial": 1,
        "Status": "Active",
        "UserName": {
          "Ref": "PipelineUser"
        }
      }
    },
    "PipelineUserSecretKey": {
      "Type": "AWS::SecretsManager::Secret",
      "Condition": "MissingPipelineUser",
      "Properties": {
        "SecretString": {
          "Fn::Sub": "{\"aws_access_key_id\": \"${PipelineUserAccessKey}\", \"aws_secret_access_key\": \"${PipelineUserAccessKey.SecretAccessKey}\"}"
        }
      }
    },
    "CloudFormationExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Condition": "MissingCloudFormationExecutionRole",
      "Properties": {
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          }
        ],
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "cloudformation.amazonaws.com"
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "GrantCloudFormationFullAccess",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": "*",
                  "Resource": "*"
                }
              ]
            }
          }
        ]
      }
    },
    "PipelineExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Condition": "MissingPipelineExecutionRole",
      "Properties": {
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          },
          {
            "Key": "Role",
            "Value": "pipeline-execution-role"
          }
        ],
        "AssumeRolePolicyDocument": {
          "Fn::If": [
            "DontUseOidc",
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": [
                      {
                        "Fn::If": [
                          "MissingPipelineUser",
                          {
                            "Fn::GetAtt": "PipelineUser.Arn"
                          },
                          {
                            "Ref": "PipelineUserArn"
                          }
                        ]
                      }
                    ]
                  },
                  "Action": [
                    "sts:AssumeRole"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": [
                      {
                        "Fn::If": [
                          "MissingPipelineUser",
                          {
                            "Ref": "AWS::AccountId"
                          },
                          {
                            "Fn::Select": [
                              4,
                              {
                                "Fn::Split": [
                                  ":",
                                  {
                                    "Ref": "PipelineUserArn"
                                  }
                                ]
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  },
                  "Action": [
                    "sts:AssumeRole"
                  ],
                  "Condition": {
                    "StringEquals": {
                      "aws:PrincipalTag/Role": "aws-sam-pipeline-codebuild-service-role"
                    }
                  }
                }
              ]
            },
            {
              "Fn::Sub": [
                "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"Federated\": \"arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/${Url}\"\n      },\n      \"Action\": \"sts:AssumeRoleWithWebIdentity\",\n      \"Condition\": {\n        \"ForAllValues:StringLike\": {\n          \"${Url}:aud\": \"${OidcClientId}\",\n          \"${Url}:sub\":  \"${SubjectClaim}\"\n        }\n      }\n    }\n  ]\n}\n",
                {
                  "Url": {
                    "Fn::Select": [
                      1,
                      {
                        "Fn::Split": [
                          "//",
                          {
                            "Ref": "OidcProviderUrl"
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }
          ]
        }
      }
    },
    "ArtifactsBucket": {
      "Type": "AWS::S3::Bucket",
      "Condition": "MissingArtifactsBucket",
      "DeletionPolicy": "Retain",
      "Properties": {
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          }
        ],
        "LoggingConfiguration": {
          "DestinationBucketName": {
            "Ref": "ArtifactsLoggingBucket"
          },
          "LogFilePrefix": "artifacts-logs"
        },
        "VersioningConfiguration": {
          "Status": "Enabled"
        },
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "ArtifactsBucketPolicy": {
      "Type": "AWS::S3::BucketPolicy",
      "Condition": "MissingArtifactsBucket",
      "Properties": {
        "Bucket": {
          "Ref": "ArtifactsBucket"
        },
        "PolicyDocument": {
          "Statement": [
            {
              "Effect": "Deny",
              "Action": "s3:*",
              "Principal": "*",
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      {
                        "Fn::GetAtt": "ArtifactsBucket.Arn"
                      },
                      "/*"
                    ]
                  ]
                },
                {
                  "Fn::GetAtt": "ArtifactsBucket.Arn"
                }
              ],
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": false
                }
              }
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:GetObject*",
                "s3:PutObject*",
                "s3:GetBucket*",
                "s3:List*"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      {
                        "Fn::GetAtt": "ArtifactsBucket.Arn"
                      },
                      "/*"
                    ]
                  ]
                },
                {
                  "Fn::GetAtt": "ArtifactsBucket.Arn"
                }
              ],
              "Principal": {
                "AWS": [
                  {
                    "Fn::If": [
                      "MissingPipelineExecutionRole",
                      {
                        "Fn::GetAtt": "PipelineExecutionRole.Arn"
                      },
                      {
                        "Ref": "PipelineExecutionRoleArn"
                      }
                    ]
                  },
                  {
                    "Fn::If": [
                      "MissingCloudFormationExecutionRole",
                      {
                        "Fn::GetAtt": "CloudFormationExecutionRole.Arn"
                      },
                      {
                        "Ref": "CloudFormationExecutionRoleArn"
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }
      }
    },
    "ArtifactsLoggingBucket": {
      "Type": "AWS::S3::Bucket",
      "Condition": "MissingArtifactsBucket",
      "DeletionPolicy": "Retain",
      "Properties": {
        "AccessControl": "LogDeliveryWrite",
        "OwnershipControls": {
          "Rules": [
            {
              "ObjectOwnership": "ObjectWriter"
            }
          ]
        },
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          }
        ],
        "VersioningConfiguration": {
          "Status": "Enabled"
        },
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "ArtifactsLoggingBucketPolicy": {
      "Type": "AWS::S3::BucketPolicy",
      "Condition": "MissingArtifactsBucket",
      "Properties": {
        "Bucket": {
          "Ref": "ArtifactsLoggingBucket"
        },
        "PolicyDocument": {
          "Statement": [
            {
              "Effect": "Deny",
              "Action": "s3:*",
              "Principal": "*",
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      {
                        "Fn::GetAtt": "ArtifactsLoggingBucket.Arn"
                      },
                      "/*"
                    ]
                  ]
                },
                {
                  "Fn::GetAtt": "ArtifactsLoggingBucket.Arn"
                }
              ],
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": false
                }
              }
            }
          ]
        }
      }
    },
    "PipelineExecutionRolePermissionPolicy": {
      "Type": "AWS::IAM::Policy",
      "Condition": "MissingPipelineExecutionRole",
      "Properties": {
        "PolicyName": "PipelineExecutionRolePermissions",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": "iam:PassRole",
              "Resource": {
                "Fn::If": [
                  "MissingCloudFormationExecutionRole",
                  {
                    "Fn::GetAtt": "CloudFormationExecutionRole.Arn"
                  },
                  {
                    "Ref": "CloudFormationExecutionRoleArn"
                  }
                ]
              }
            },
            {
              "Effect": "Allow",
              "Action": [
                "cloudformation:CreateChangeSet",
                "cloudformation:DescribeChangeSet",
                "cloudformation:ExecuteChangeSet",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStacks",
                "cloudformation:GetTemplate",
                "cloudformation:GetTemplateSummary",
                "cloudformation:DescribeStackResource"
              ],
              "Resource": "*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:DeleteObject",
                "s3:GetObject*",
                "s3:PutObject*",
                "s3:GetBucket*",
                "s3:List*"
              ],
              "Resource": {
                "Fn::If": [
                  "MissingArtifactsBucket",
                  [
                    {
                      "Fn::Join": [
                        "",
                        [
                          {
                            "Fn::GetAtt": "ArtifactsBucket.Arn"
                          },
                          "/*"
                        ]
                      ]
                    },
                    {
                      "Fn::GetAtt": "ArtifactsBucket.Arn"
                    }
                  ],
                  [
                    {
                      "Fn::Join": [
                        "",
                        [
                          {
                            "Ref": "ArtifactsBucketArn"
                          },
                          "/*"
                        ]
                      ]
                    },
                    {
                      "Ref": "ArtifactsBucketArn"
                    }
                  ]
                ]
              }
            },
            {
              "Fn::If": [
                "ShouldHaveImageRepository",
                {
                  "Effect": "Allow",
                  "Action": "ecr:GetAuthorizationToken",
                  "Resource": "*"
                },
                {
                  "Ref": "AWS::NoValue"
                }
              ]
            },
            {
              "Fn::If": [
                "ShouldHaveImageRepository",
                {
                  "Effect": "Allow",
                  "Action": [
                    "ecr:GetDownloadUrlForLayer",
                    "ecr:BatchDeleteImage",
                    "ecr:BatchGetImage",
                    "ecr:BatchCheckLayerAvailability",
                    "ecr:PutImage",
                    "ecr:InitiateLayerUpload",
                    "ecr:UploadLayerPart",
                    "ecr:CompleteLayerUpload"
                  ],
                  "Resource": {
                    "Fn::If": [
                      "MissingImageRepository",
                      {
                        "Fn::GetAtt": "ImageRepository.Arn"
                      },
                      {
                        "Ref": "ImageRepositoryArn"
                      }
                    ]
                  }
                },
                {
                  "Ref": "AWS::NoValue"
                }
              ]
            }
          ]
        },
        "Roles": [
          {
            "Ref": "PipelineExecutionRole"
          }
        ]
      }
    },
    "ImageRepository": {
      "Type": "AWS::ECR::Repository",
      "Condition": "MissingImageRepository",
      "Properties": {
        "RepositoryPolicyText": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "LambdaECRImageRetrievalPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              },
              "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:GetRepositoryPolicy",
                "ecr:SetRepositoryPolicy",
                "ecr:DeleteRepositoryPolicy"
              ]
            },
            {
              "Sid": "AllowPushPull",
              "Effect": "Allow",
              "Principal": {
                "AWS": [
                  {
                    "Fn::If": [
                      "MissingPipelineExecutionRole",
                      {
                        "Fn::GetAtt": "PipelineExecutionRole.Arn"
                      },
                      {
                        "Ref": "PipelineExecutionRoleArn"
                      }
                    ]
                  },
                  {
                    "Fn::If": [
                      "MissingCloudFormationExecutionRole",
                      {
                        "Fn::GetAtt": "CloudFormationExecutionRole.Arn"
                      },
                      {
                        "Ref": "CloudFormationExecutionRoleArn"
                      }
                    ]
                  }
                ]
              },
              "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload"
              ]
            }
          ]
        }
      }
    }
  },
  "Conditions": {
    "MissingOidcProvider": {
      "Fn::Equals": [
        {
          "Ref": "CreateNewOidcProvider"
        },
        "true"
      ]
    },
    "DontUseOidc": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            {
              "Ref": "UseOidcProvider"
            },
            "true"
          ]
        }
      ]
    },
    "MissingPipelineUser": {
      "Fn::And": [
        {
          "Condition": "DontUseOidc"
        },
        {
          "Fn::Equals": [
            {
              "Ref": "PipelineUserArn"
            },
            ""
          ]
        }
      ]
    },
    "MissingPipelineExecutionRole": {
      "Fn::Equals": [
        {
          "Ref": "PipelineExecutionRoleArn"
        },
        ""
      ]
    },
    "MissingCloudFormationExecutionRole": {
      "Fn::Equals": [
        {
          "Ref": "CloudFormationExecutionRoleArn"
        },
        ""
      ]
    },
    "MissingArtifactsBucket": {
      "Fn::Equals": [
        {
          "Ref": "ArtifactsBucketArn"
        },
        ""
      ]
    },
    "ShouldHaveImageRepository": {
      "Fn::Or": [
        {
          "Fn::Equals": [
            {
              "Ref": "CreateImageRepository"
            },
            "true"
          ]
        },
        {
          "Fn::Not": [
            {
              "Fn::Equals": [
                {
                  "Ref": "ImageRepositoryArn"
                },
                ""
              ]
            }
          ]
        }
      ]
    },
    "MissingImageRepository": {
      "Fn::And": [
        {
          "Condition": "ShouldHaveImageRepository"
        },
        {
          "Fn::Equals": [
            {
              "Ref": "ImageRepositoryArn"
            },
            ""
          ]
        }
      ]
    }
  }
}
``` 
</details>

<details>

<summary>
The resources which Cloudformation creates are </summary>

- PipelineUserSecretKey - AWS::SecretsManager::Secret 
- PipelineUserAccessKey - AWS::IAM::AccessKey
- PipelineUser - AWS::IAM::User
- PipelineExecutionRolePermissionPolicy - AWS::IAM::Policy
- PipelineExecutionRole - AWS::IAM::Role
- CloudFormationExecutionRole - AWS::IAM::Role
- ArtifactsLoggingBucketPolicy - AWS::S3::BucketPolicy
- ArtifactsLoggingBucket - AWS::S3::Bucket
- ArtifactsBucketPolicy - AWS::S3::BucketPolicy
- ArtifactsBucket - AWS::S3::Bucket

</details>

The databases to be created are mentioned in this ticket #55 

Services being used are mentioned in this ticket #92

**Comment by lakshayman** [comment]
These are roles required for the user who accesses it or the user using who credential we run CI CD?
I think you have to access Lambda too so you role for it.

It will much easier if you mention the role names. I created this for identity service https://github.com/Real-Dev-Squad/identity-service/issues/55

**Comment by vikhyat187** [comment]
These roles are required to the user to setup the service in prod, will be creating the **pipeline role using cloudformation**

Will be also needing few more roles along with the ones in identity service as we implemented the **limit on the no of invocations**, so this will require permissions to Invoke other lambdas, mark the reserved concurrency 0, Call dynamodb and update values there.

**Comment by lakshayman** [comment]
You have a pipeline setup in the repo. I am still unable to understand why you need these permissions, take some time from Tejas or Ankush, sit and set up the whole process. Giving prod access to every project owner is not good. You can write and RFC for the whole process, I did that and Ankush did the whole setup for identity service.

**Comment by lakshayman** [comment]
You can write the exact policy name it will be easier for anyone creating the user. You can also mention that the user we are going to create doesn't need console access as it only used for CI CD. Otherwise look good to me.

**Comment by vikhyat187** [comment]
Hi @lakshayman the above roles are for My user(vikhyatbhatnagar) and using this user will create the pipeline user.
> Create Dynamodb table permission
We will have to create IAM roles with additional permissions for lambdas
apigateway: permissions to create API (GET, PUT, POST, PATCH)
IAM Tag / Untag role
AWS lambda (all permissions)
Cloudformation (all permissions)
S3 create buckets

**Comment by lakshayman** [comment]
Ok so for that you don't have to create a user, you have to write the process in a RFC and ask any super user to do the setup. 
IAM access is not provided to any project owner. It's a one time setup, that can be done by any super user.
If every project owner has the IAM access, it will raise security concerns.

**Comment by vikhyat187** [comment]
Hi @iamitprakash can you please create these resources in the AWS account.

<details>
<summary>Attaching the cloudformation template code here 
</summary>

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "PipelineUserArn": {
      "Type": "String"
    },
    "PipelineExecutionRoleArn": {
      "Type": "String"
    },
    "CloudFormationExecutionRoleArn": {
      "Type": "String"
    },
    "ArtifactsBucketArn": {
      "Type": "String"
    },
    "CreateImageRepository": {
      "Type": "String",
      "Default": false,
      "AllowedValues": [
        true,
        false
      ]
    },
    "ImageRepositoryArn": {
      "Type": "String"
    },
    "IdentityProviderThumbprint": {
      "Type": "String"
    },
    "OidcClientId": {
      "Type": "String"
    },
    "OidcProviderUrl": {
      "Type": "String"
    },
    "UseOidcProvider": {
      "Type": "String",
      "AllowedValues": [
        true,
        false
      ]
    },
    "SubjectClaim": {
      "Type": "String"
    },
    "CreateNewOidcProvider": {
      "Type": "String",
      "AllowedValues": [
        true,
        false
      ]
    }
  },
  "Outputs": {
    "PipelineUser": {
      "Description": "ARN of the Pipeline IAM User",
      "Value": {
        "Fn::If": [
          "MissingPipelineUser",
          {
            "Fn::GetAtt": "PipelineUser.Arn"
          },
          {
            "Ref": "PipelineUserArn"
          }
        ]
      }
    },
    "PipelineUserSecretKey": {
      "Description": "AWS Access Key and Secret Key of pipeline user.",
      "Condition": "MissingPipelineUser",
      "Value": {
        "Ref": "PipelineUserSecretKey"
      }
    },
    "CloudFormationExecutionRole": {
      "Description": "ARN of the IAM Role(CloudFormationExecutionRole)",
      "Value": {
        "Fn::If": [
          "MissingCloudFormationExecutionRole",
          {
            "Fn::GetAtt": "CloudFormationExecutionRole.Arn"
          },
          {
            "Ref": "CloudFormationExecutionRoleArn"
          }
        ]
      }
    },
    "PipelineExecutionRole": {
      "Description": "ARN of the IAM Role(PipelineExecutionRole)",
      "Value": {
        "Fn::If": [
          "MissingPipelineExecutionRole",
          {
            "Fn::GetAtt": "PipelineExecutionRole.Arn"
          },
          {
            "Ref": "PipelineExecutionRoleArn"
          }
        ]
      }
    },
    "ArtifactsBucket": {
      "Description": "ARN of the Artifacts bucket",
      "Value": {
        "Fn::If": [
          "MissingArtifactsBucket",
          {
            "Fn::GetAtt": "ArtifactsBucket.Arn"
          },
          {
            "Ref": "ArtifactsBucketArn"
          }
        ]
      }
    },
    "ImageRepository": {
      "Description": "ARN of the ECR image repository",
      "Condition": "ShouldHaveImageRepository",
      "Value": {
        "Fn::If": [
          "MissingImageRepository",
          {
            "Fn::GetAtt": "ImageRepository.Arn"
          },
          {
            "Ref": "ImageRepositoryArn"
          }
        ]
      }
    }
  },
  "Resources": {
    "OidcProvider": {
      "Type": "AWS::IAM::OIDCProvider",
      "Condition": "MissingOidcProvider",
      "Properties": {
        "ClientIdList": [
          {
            "Ref": "OidcClientId"
          }
        ],
        "ThumbprintList": [
          {
            "Ref": "IdentityProviderThumbprint"
          }
        ],
        "Url": {
          "Ref": "OidcProviderUrl"
        }
      }
    },
    "PipelineUser": {
      "Type": "AWS::IAM::User",
      "Condition": "MissingPipelineUser",
      "Properties": {
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          }
        ],
        "Policies": [
          {
            "PolicyName": "AssumeRoles",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "sts:AssumeRole"
                  ],
                  "Resource": "*",
                  "Condition": {
                    "StringEquals": {
                      "aws:ResourceTag/Role": "pipeline-execution-role"
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "PipelineUserAccessKey": {
      "Type": "AWS::IAM::AccessKey",
      "Condition": "MissingPipelineUser",
      "Properties": {
        "Serial": 1,
        "Status": "Active",
        "UserName": {
          "Ref": "PipelineUser"
        }
      }
    },
    "PipelineUserSecretKey": {
      "Type": "AWS::SecretsManager::Secret",
      "Condition": "MissingPipelineUser",
      "Properties": {
        "SecretString": {
          "Fn::Sub": "{\"aws_access_key_id\": \"${PipelineUserAccessKey}\", \"aws_secret_access_key\": \"${PipelineUserAccessKey.SecretAccessKey}\"}"
        }
      }
    },
    "CloudFormationExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Condition": "MissingCloudFormationExecutionRole",
      "Properties": {
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          }
        ],
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "cloudformation.amazonaws.com"
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "GrantCloudFormationFullAccess",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": "*",
                  "Resource": "*"
                }
              ]
            }
          }
        ]
      }
    },
    "PipelineExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Condition": "MissingPipelineExecutionRole",
      "Properties": {
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          },
          {
            "Key": "Role",
            "Value": "pipeline-execution-role"
          }
        ],
        "AssumeRolePolicyDocument": {
          "Fn::If": [
            "DontUseOidc",
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": [
                      {
                        "Fn::If": [
                          "MissingPipelineUser",
                          {
                            "Fn::GetAtt": "PipelineUser.Arn"
                          },
                          {
                            "Ref": "PipelineUserArn"
                          }
                        ]
                      }
                    ]
                  },
                  "Action": [
                    "sts:AssumeRole"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": [
                      {
                        "Fn::If": [
                          "MissingPipelineUser",
                          {
                            "Ref": "AWS::AccountId"
                          },
                          {
                            "Fn::Select": [
                              4,
                              {
                                "Fn::Split": [
                                  ":",
                                  {
                                    "Ref": "PipelineUserArn"
                                  }
                                ]
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  },
                  "Action": [
                    "sts:AssumeRole"
                  ],
                  "Condition": {
                    "StringEquals": {
                      "aws:PrincipalTag/Role": "aws-sam-pipeline-codebuild-service-role"
                    }
                  }
                }
              ]
            },
            {
              "Fn::Sub": [
                "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"Federated\": \"arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/${Url}\"\n      },\n      \"Action\": \"sts:AssumeRoleWithWebIdentity\",\n      \"Condition\": {\n        \"ForAllValues:StringLike\": {\n          \"${Url}:aud\": \"${OidcClientId}\",\n          \"${Url}:sub\":  \"${SubjectClaim}\"\n        }\n      }\n    }\n  ]\n}\n",
                {
                  "Url": {
                    "Fn::Select": [
                      1,
                      {
                        "Fn::Split": [
                          "//",
                          {
                            "Ref": "OidcProviderUrl"
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }
          ]
        }
      }
    },
    "ArtifactsBucket": {
      "Type": "AWS::S3::Bucket",
      "Condition": "MissingArtifactsBucket",
      "DeletionPolicy": "Retain",
      "Properties": {
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          }
        ],
        "LoggingConfiguration": {
          "DestinationBucketName": {
            "Ref": "ArtifactsLoggingBucket"
          },
          "LogFilePrefix": "artifacts-logs"
        },
        "VersioningConfiguration": {
          "Status": "Enabled"
        },
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "ArtifactsBucketPolicy": {
      "Type": "AWS::S3::BucketPolicy",
      "Condition": "MissingArtifactsBucket",
      "Properties": {
        "Bucket": {
          "Ref": "ArtifactsBucket"
        },
        "PolicyDocument": {
          "Statement": [
            {
              "Effect": "Deny",
              "Action": "s3:*",
              "Principal": "*",
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      {
                        "Fn::GetAtt": "ArtifactsBucket.Arn"
                      },
                      "/*"
                    ]
                  ]
                },
                {
                  "Fn::GetAtt": "ArtifactsBucket.Arn"
                }
              ],
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": false
                }
              }
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:GetObject*",
                "s3:PutObject*",
                "s3:GetBucket*",
                "s3:List*"
              ],
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      {
                        "Fn::GetAtt": "ArtifactsBucket.Arn"
                      },
                      "/*"
                    ]
                  ]
                },
                {
                  "Fn::GetAtt": "ArtifactsBucket.Arn"
                }
              ],
              "Principal": {
                "AWS": [
                  {
                    "Fn::If": [
                      "MissingPipelineExecutionRole",
                      {
                        "Fn::GetAtt": "PipelineExecutionRole.Arn"
                      },
                      {
                        "Ref": "PipelineExecutionRoleArn"
                      }
                    ]
                  },
                  {
                    "Fn::If": [
                      "MissingCloudFormationExecutionRole",
                      {
                        "Fn::GetAtt": "CloudFormationExecutionRole.Arn"
                      },
                      {
                        "Ref": "CloudFormationExecutionRoleArn"
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }
      }
    },
    "ArtifactsLoggingBucket": {
      "Type": "AWS::S3::Bucket",
      "Condition": "MissingArtifactsBucket",
      "DeletionPolicy": "Retain",
      "Properties": {
        "AccessControl": "LogDeliveryWrite",
        "OwnershipControls": {
          "Rules": [
            {
              "ObjectOwnership": "ObjectWriter"
            }
          ]
        },
        "Tags": [
          {
            "Key": "ManagedStackSource",
            "Value": "AwsSamCli"
          }
        ],
        "VersioningConfiguration": {
          "Status": "Enabled"
        },
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "ArtifactsLoggingBucketPolicy": {
      "Type": "AWS::S3::BucketPolicy",
      "Condition": "MissingArtifactsBucket",
      "Properties": {
        "Bucket": {
          "Ref": "ArtifactsLoggingBucket"
        },
        "PolicyDocument": {
          "Statement": [
            {
              "Effect": "Deny",
              "Action": "s3:*",
              "Principal": "*",
              "Resource": [
                {
                  "Fn::Join": [
                    "",
                    [
                      {
                        "Fn::GetAtt": "ArtifactsLoggingBucket.Arn"
                      },
                      "/*"
                    ]
                  ]
                },
                {
                  "Fn::GetAtt": "ArtifactsLoggingBucket.Arn"
                }
              ],
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": false
                }
              }
            }
          ]
        }
      }
    },
    "PipelineExecutionRolePermissionPolicy": {
      "Type": "AWS::IAM::Policy",
      "Condition": "MissingPipelineExecutionRole",
      "Properties": {
        "PolicyName": "PipelineExecutionRolePermissions",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": "iam:PassRole",
              "Resource": {
                "Fn::If": [
                  "MissingCloudFormationExecutionRole",
                  {
                    "Fn::GetAtt": "CloudFormationExecutionRole.Arn"
                  },
                  {
                    "Ref": "CloudFormationExecutionRoleArn"
                  }
                ]
              }
            },
            {
              "Effect": "Allow",
              "Action": [
                "cloudformation:CreateChangeSet",
                "cloudformation:DescribeChangeSet",
                "cloudformation:ExecuteChangeSet",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStacks",
                "cloudformation:GetTemplate",
                "cloudformation:GetTemplateSummary",
                "cloudformation:DescribeStackResource"
              ],
              "Resource": "*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:DeleteObject",
                "s3:GetObject*",
                "s3:PutObject*",
                "s3:GetBucket*",
                "s3:List*"
              ],
              "Resource": {
                "Fn::If": [
                  "MissingArtifactsBucket",
                  [
                    {
                      "Fn::Join": [
                        "",
                        [
                          {
                            "Fn::GetAtt": "ArtifactsBucket.Arn"
                          },
                          "/*"
                        ]
                      ]
                    },
                    {
                      "Fn::GetAtt": "ArtifactsBucket.Arn"
                    }
                  ],
                  [
                    {
                      "Fn::Join": [
                        "",
                        [
                          {
                            "Ref": "ArtifactsBucketArn"
                          },
                          "/*"
                        ]
                      ]
                    },
                    {
                      "Ref": "ArtifactsBucketArn"
                    }
                  ]
                ]
              }
            },
            {
              "Fn::If": [
                "ShouldHaveImageRepository",
                {
                  "Effect": "Allow",
                  "Action": "ecr:GetAuthorizationToken",
                  "Resource": "*"
                },
                {
                  "Ref": "AWS::NoValue"
                }
              ]
            },
            {
              "Fn::If": [
                "ShouldHaveImageRepository",
                {
                  "Effect": "Allow",
                  "Action": [
                    "ecr:GetDownloadUrlForLayer",
                    "ecr:BatchDeleteImage",
                    "ecr:BatchGetImage",
                    "ecr:BatchCheckLayerAvailability",
                    "ecr:PutImage",
                    "ecr:InitiateLayerUpload",
                    "ecr:UploadLayerPart",
                    "ecr:CompleteLayerUpload"
                  ],
                  "Resource": {
                    "Fn::If": [
                      "MissingImageRepository",
                      {
                        "Fn::GetAtt": "ImageRepository.Arn"
                      },
                      {
                        "Ref": "ImageRepositoryArn"
                      }
                    ]
                  }
                },
                {
                  "Ref": "AWS::NoValue"
                }
              ]
            }
          ]
        },
        "Roles": [
          {
            "Ref": "PipelineExecutionRole"
          }
        ]
      }
    },
    "ImageRepository": {
      "Type": "AWS::ECR::Repository",
      "Condition": "MissingImageRepository",
      "Properties": {
        "RepositoryPolicyText": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "LambdaECRImageRetrievalPolicy",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              },
              "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:GetRepositoryPolicy",
                "ecr:SetRepositoryPolicy",
                "ecr:DeleteRepositoryPolicy"
              ]
            },
            {
              "Sid": "AllowPushPull",
              "Effect": "Allow",
              "Principal": {
                "AWS": [
                  {
                    "Fn::If": [
                      "MissingPipelineExecutionRole",
                      {
                        "Fn::GetAtt": "PipelineExecutionRole.Arn"
                      },
                      {
                        "Ref": "PipelineExecutionRoleArn"
                      }
                    ]
                  },
                  {
                    "Fn::If": [
                      "MissingCloudFormationExecutionRole",
                      {
                        "Fn::GetAtt": "CloudFormationExecutionRole.Arn"
                      },
                      {
                        "Ref": "CloudFormationExecutionRoleArn"
                      }
                    ]
                  }
                ]
              },
              "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload"
              ]
            }
          ]
        }
      }
    }
  },
  "Conditions": {
    "MissingOidcProvider": {
      "Fn::Equals": [
        {
          "Ref": "CreateNewOidcProvider"
        },
        "true"
      ]
    },
    "DontUseOidc": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            {
              "Ref": "UseOidcProvider"
            },
            "true"
          ]
        }
      ]
    },
    "MissingPipelineUser": {
      "Fn::And": [
        {
          "Condition": "DontUseOidc"
        },
        {
          "Fn::Equals": [
            {
              "Ref": "PipelineUserArn"
            },
            ""
          ]
        }
      ]
    },
    "MissingPipelineExecutionRole": {
      "Fn::Equals": [
        {
          "Ref": "PipelineExecutionRoleArn"
        },
        ""
      ]
    },
    "MissingCloudFormationExecutionRole": {
      "Fn::Equals": [
        {
          "Ref": "CloudFormationExecutionRoleArn"
        },
        ""
      ]
    },
    "MissingArtifactsBucket": {
      "Fn::Equals": [
        {
          "Ref": "ArtifactsBucketArn"
        },
        ""
      ]
    },
    "ShouldHaveImageRepository": {
      "Fn::Or": [
        {
          "Fn::Equals": [
            {
              "Ref": "CreateImageRepository"
            },
            "true"
          ]
        },
        {
          "Fn::Not": [
            {
              "Fn::Equals": [
                {
                  "Ref": "ImageRepositoryArn"
                },
                ""
              ]
            }
          ]
        }
      ]
    },
    "MissingImageRepository": {
      "Fn::And": [
        {
          "Condition": "ShouldHaveImageRepository"
        },
        {
          "Fn::Equals": [
            {
              "Ref": "ImageRepositoryArn"
            },
            ""
          ]
        }
      ]
    }
  }
}
``` 
</details>

**Comment by vikhyat187** [comment]
The service is deployed, so closing this
